name: Build and run on build machine

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

concurrency:
  group: buildbox-main
  cancel-in-progress: false

jobs:
  build_run:
    # Only run if the Tests workflow concluded successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build & run
        env:
          PFX_PASSWORD: ${{ secrets.PFX_PASSWORD }}
          PERSIST_IPTABLES: "0"
        run: |
          chmod +x src/deploy/build-run-locally.sh
          cd src/deploy
          ./build-run-locally.sh