name: Build and run on build machine

on:
  push:
    branches: ["main"]

concurrency:
  group: buildbox-main
  cancel-in-progress: false

jobs:
  build_run:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build & run
        env:
          PFX_PASSWORD: ${{ secrets.PFX_PASSWORD }}
          PERSIST_IPTABLES: "0"
          # optionally also:
          # OPEN_PORTS: "0"
        run: |
          chmod +x src/deploy/build-run-locally.sh
          cd src/deploy
          ./build-run-locally.sh
